contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
canonifyURLs = true
baseURL = "/"
title = "Dave F. Kleinschmidt"

[author]
        name = "Dave F. Kleinschmidt"
        github = "kleinschmidt"
        twitter = "kleinschmidt"
